Feature: AsIngested Coordinates Indexing
  This feature deals with validation of AsIngestedCoordinates properties in Elastic Search.

  @as-ingested-coordinates
  Scenario Outline: Ingest the record and Index in the Elastic with AsIngestedCoordinates properties
    Given the schema is created with the following kind
      | kind   | index   | schemaFile   |
      | <kind> | <index> | <schemaFile> |
    When I ingest records with the <recordFile> with <acl> for a given <kind>
    Then I should be able search <number> documents for the <index> by flattened inner properties (<flattened_inner_field>, <flattened_inner_value>)
    Then I should get <inner_field> in search response for the <index>

    Examples:
      | kind                                                              | recordFile                                    | number | index                                                             | schemaFile                                    | acl                            | flattened_inner_field                                                                 | flattened_inner_value                                                     | inner_field                                                                  |
      | "tenant1:wks<timestamp>:master-data--Wellbore:2.0.5"     | "r3-index_record_wks_master_coordinates"      | 1      | "tenant1-wks<timestamp>-master-data--wellbore-2.0.5"     | r3-index_record_wks_master_coordinates      | "data.default.viewers@tenant1" | "data.ProjectedBottomHoleLocation.AsIngestedCoordinates.CoordinateReferenceSystemID"  | "osdu:reference-data--CoordinateReferenceSystem:ED_1950_UTM_Zone_31N:"    | "ProjectedBottomHoleLocation.AsIngestedCoordinates.persistableReferenceCrs"  |
      | "tenant1:wks<timestamp>:master-data--Wellbore:2.0.5"     | "r3-index_record_wks_master_coordinates"      | 1      | "tenant1-wks<timestamp>-master-data--wellbore-2.0.5"     | r3-index_record_wks_master_coordinates      | "data.default.viewers@tenant1" | "data.SpatialLocation.AsIngestedCoordinates.CoordinateReferenceSystemID"              | "osdu:reference-data--CoordinateReferenceSystem:ED_1950_UTM_Zone_31N:"    | "SpatialLocation.AsIngestedCoordinates.persistableReferenceCrs"              |
      | "tenant1:indexer<timestamp>:virtual-properties-coordinates-Integration:1.0.0" | "index_record_virtual_properties_coordinates" | 1      | "tenant1-indexer<timestamp>-virtual-properties-coordinates-integration-1.0.0" | index_record_virtual_properties_coordinates | "data.default.viewers@tenant1" | "data.ProjectedBottomHoleLocation.AsIngestedCoordinates.CoordinateReferenceSystemID"  | "osdu:reference-data--CoordinateReferenceSystem:WGS_1984_World_Mercator:" | "ProjectedBottomHoleLocation.AsIngestedCoordinates.persistableReferenceCrs"  |
      | "tenant1:indexer<timestamp>:virtual-properties-coordinates-Integration:1.0.0" | "index_record_virtual_properties_coordinates" | 2      | "tenant1-indexer<timestamp>-virtual-properties-coordinates-integration-1.0.0" | index_record_virtual_properties_coordinates | "data.default.viewers@tenant1" | "data.GeographicBottomHoleLocation.AsIngestedCoordinates.CoordinateReferenceSystemID" | "osdu:reference-data--CoordinateReferenceSystem:WGS_1984_World_Mercator:" | "GeographicBottomHoleLocation.AsIngestedCoordinates.persistableReferenceCrs" |
      | "tenant1:indexer<timestamp>:virtual-properties-coordinates-Integration:1.0.0" | "index_record_virtual_properties_coordinates" | 3      | "tenant1-indexer<timestamp>-virtual-properties-coordinates-integration-1.0.0" | index_record_virtual_properties_coordinates | "data.default.viewers@tenant1" | "data.SpatialLocation.AsIngestedCoordinates.CoordinateReferenceSystemID"              | "osdu:reference-data--CoordinateReferenceSystem:WGS_1984_World_Mercator:" | "SpatialLocation.AsIngestedCoordinates.persistableReferenceCrs"              |

  @as-ingested-coordinates
  Scenario Outline: Ingest the record and Index in the Elastic with AsIngestedCoordinates properties and search by coordinates
    Given the schema is created with the following kind
      | kind   | index   | schemaFile   |
      | <kind> | <index> | <schemaFile> |
    When I ingest records with the <recordFile> with <acl> for a given <kind>
    Then I should be able search <number> documents for the <index> by bounding box query with points (<topPointX>, <bottomPointX>) on field <pointX> and points (<topPointY>, <bottomPointY>) on field <pointY>

    Examples:
      | kind                                                              | recordFile                                    | number | index                                                             | schemaFile                                    | acl                            | pointX                                                                | topPointX   | bottomPointX | pointY                                                                | topPointY    | bottomPointY |
      | "tenant1:wks<timestamp>:master-data--Wellbore:2.0.5"                          | "r3-index_record_wks_master_coordinates"      | 1      | "tenant1-wks<timestamp>-master-data--wellbore-2.0.5"                          | r3-index_record_wks_master_coordinates      | "data.default.viewers@tenant1" | "data.ProjectedBottomHoleLocation.AsIngestedCoordinates.FirstPoint.X" | 710000      | 700000       | "data.ProjectedBottomHoleLocation.AsIngestedCoordinates.FirstPoint.Y" | 5800000      | 5700000      |
      | "tenant1:indexer<timestamp>:virtual-properties-coordinates-Integration:1.0.0" | "index_record_virtual_properties_coordinates" | 1      | "tenant1-indexer<timestamp>-virtual-properties-coordinates-integration-1.0.0" | index_record_virtual_properties_coordinates | "data.default.viewers@tenant1" | "data.ProjectedBottomHoleLocation.AsIngestedCoordinates.FirstPoint.X" | 2600000     | 2500000      | "data.ProjectedBottomHoleLocation.AsIngestedCoordinates.FirstPoint.Y" | -3500000     | -3600000     |
      | "tenant1:indexer<timestamp>:decimation-Integration:1.0.0"                    | "index_record_seismic_survey_coordinates"     | 1      | "tenant1-indexer<timestamp>-decimation-integration-1.0.0"                    | index_record_seismic_survey_coordinates     | "data.default.viewers@tenant1" | "data.SpatialLocation.AsIngestedCoordinates.FirstPoint.X"             | 1151940     | 1151930      | "data.SpatialLocation.AsIngestedCoordinates.FirstPoint.Y"             | 4843810      | 4843800      |
      | "tenant1:indexer<timestamp>:virtual-properties-coordinates-Integration:1.0.0" | "index_record_virtual_properties_coordinates" | 1      | "tenant1-indexer<timestamp>-virtual-properties-coordinates-integration-1.0.0" | index_record_virtual_properties_coordinates | "data.default.viewers@tenant1" | "data.ProjectedBottomHoleLocation.AsIngestedCoordinates.FirstPoint.X" | 2504888.139 | 2504888.138  | "data.ProjectedBottomHoleLocation.AsIngestedCoordinates.FirstPoint.Y" | -3525752.639 | -3525752.640 |
